-- 코드를 작성해주세요
# 1. 아이템의 희귀도가 rare인 아이템들 찾기
# 2. 1에서 구한 아이템들 ITEM_ID랑 ITEM_TREE의 PARENT_ITEM_ID 랑 조인하기 
# 3. 3에서 조인후 나오는 ITEM_ID 를 다시 ITEM_INFO 와 조인 해서 RARITY랑 ITEM_NAME ITEM_ID 출력?

SELECT L.ITEM_ID,L.ITEM_NAME,L.RARITY
FROM ITEM_INFO L 
JOIN 
(SELECT ITEM_ID FROM ITEM_TREE T 
JOIN 
(SELECT ITEM_ID AS RARE_ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AS I
ON T.PARENT_ITEM_ID = I.RARE_ITEM_ID) AS R
ON L.ITEM_ID =R.ITEM_ID
order by L.ITEM_ID desc

